vich_uploader:
    db_driver: orm

    mappings:
       cars_images:
           uri_prefix: /assets/img
           upload_destination: '%kernel.project_dir%/public/assets/img'
        #    name : Vich\UploaderBundle\Naming\UniqiNamer